[package]
name = "footbored"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix="0.10"
actix-web = "3"
actix-rt = "1"
actix-web-actors = "3"
serde = { version = "1.0", features = ["derive"] }

